name: deploy to VPS
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_LOGIN }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: echo "test"
