name: deploy to VPS
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_LOGIN }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd apps/dungeon-story/
            docker compose pull
            docker compose up-d --remove-orphans
            docker compose ps
            docker images | grep ds-
